version: '2'

services:
  laravel:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    environment:
      - "MYSQL_DATABASE=laravel"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS laravel_testing;' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    ports:
      - 33061:3306